server:
    port: 8081

spring:
    application:
        name: china_service
    datasource:
        type: org.apache.tomcat.jdbc.pool.DataSource
        url: jdbc:mysql://127.0.0.1:3306/china?characterEncoding=UTF-8&autoReconnect=true&useSSL=false
        username: root
        password:
        driverClassName: com.mysql.jdbc.Driver
        maxActive: 500
        initialSize: 20
        minIdle: 10
        testOnBorrow: true
        testWhileIdle: true
        testOnReturn: false
        validationInterval: 30000
        validationQuery: SELECT 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 30000
        removeAbandonedTimeout: 300
        jdbcInterceptors: org.apache.tomcat.jdbc.pool.interceptor.ConnectionState;org.apache.tomcat.jdbc.pool.interceptor.StatementFinalizer
    dubbo:
        application:
            name: china_service
            id: china_service
        protocol:
            port: 20800
            name: dubbo
        registry:
            address: zookeeper://127.0.0.1:2181
            server: true









#mybatis xml 路径
mybatis:
    mapper-locations: classpath:mybatis/*.xml